# Generated by Django 5.2.4 on 2025-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Електронна пошта')),
                ('guests', models.PositiveIntegerField(verbose_name='Кількість гостей')),
                ('date', models.DateField(verbose_name='Дата бронювання')),
                ('time', models.TimeField(verbose_name='Час бронювання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
        ),
    ]
