# Generated by Django 5.2.4 on 2025-07-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='name',
        ),
    ]
