# Generated by Django 5.2.4 on 2025-07-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
