# Generated by Django 5.2.4 on 2025-07-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.IntegerField(unique=True),
        ),
    ]
